from pathlib import Path
import html, json
root=Path(__file__).parent; pages=root/'pages'; pages.mkdir(parents=True,exist_ok=True)
items=[
('01','Orbit Desk','AI workspace for calm, focused teams','saas'),('02','Morrow Coffee','Small-batch coffee for slow mornings','product'),('03','Northstar Studio','Brand strategy for ambitious founders','service'),('04','Field Notes','A weekly letter for people making things','blog'),('05','Lumen House','A light-filled stay in the city','product'),('06','Packet Zero','Your company’s first AI operating manual','service'),('07','Soft Signal','Independent music for late-night thinkers','product'),('08','Common Thread','A community for generous builders','service'),('09','Good Measure','The honest finance dashboard','saas'),('10','Wild Fig','Seasonal recipes, simply told','blog'),
('11','Relay','Ship customer work without the scramble','saas'),('12','Ember Objects','Useful things with a long life','product'),('13','Cedar & Co','A better way to plan your next chapter','service'),('14','The Long View','Notes on work, craft, and attention','blog'),('15','Cloudline','Plan trips that feel like yours','saas'),('16','Signal Fire','Turn scattered research into decisions','service'),('17','Aster','Skincare for sensitive days','product'),('18','Good Company','A private room for independent operators','service'),('19','Ledgerly','Know where your money went','saas'),('20','Sunday Index','The best links, without the noise','blog'),
('21','Tandem','Pair your best people with their best work','saas'),('22','Woven','Everyday textiles, made thoughtfully','product'),('23','Brightwork','Make the complicated clear','service'),('24','After Hours','A small magazine for big questions','blog'),('25','Mile Marker','The running plan that adapts to you','saas'),('26','Rook','Security reviews for growing companies','service'),('27','Tidepool','Objects for a quieter home','product'),('28','Open Door','A studio for meaningful gatherings','service'),('29','Gauge','Metrics your whole team can use','saas'),('30','The Kitchen Table','Recipes from people who cook every day','blog'),
('31','Hearth','A warmer way to manage projects','saas'),('32','Vale','Mineral color for modern rooms','product'),('33','Keystone','A fractional operator for the messy middle','service'),('34','Small Hours','A daily practice in noticing','blog'),('35','Vector','Turn ideas into a weekly system','saas'),('36','Good Friction','Research for better products','service'),('37','Mica','The everyday carry, edited','product'),('38','The Assembly','A salon for curious professionals','service'),('39','Plainspoken','Reports that people actually read','saas'),('40','Field Guide','A naturalist’s notebook online','blog'),
('41','Arc','Forecast what comes next','saas'),('42','Nook','Furniture for smaller lives','product'),('43','Counterpart','Executive writing with a point of view','service'),('44','The Margin','Ideas worth keeping','blog'),('45','Pace','Training that respects your life','saas'),('46','Harbor','Practical resilience for modern teams','service'),('47','Melt','Chocolate with a sense of place','product'),('48','Gather','Make your next dinner memorable','service'),('49','True North','A simpler sales pipeline','saas'),('50','The Index Card','One useful idea each Friday','blog'),
('51','Lantern','A brighter client portal','saas'),('52','Stonefruit','Preserves for the good table','product'),('53','Clearwater','Decisions for leaders in motion','service'),('54','The Workshop','Notes from a working studio','blog'),('55','Loop','The habit tracker with no guilt','saas'),('56','Ironwood','Operations that hold up under pressure','service'),('57','Kite','Playful tools for serious creators','product'),('58','Commonplace','A reading room for the internet','service'),('59','Bloom','See the shape of your business','saas'),('60','Night School','A blog for learning in public','blog'),
('61','Prism','See your customer journey clearly','saas'),('62','Brass & Pine','Kitchen tools worth handing down','product'),('63','Mainspring','Build momentum, not busywork','service'),('64','Westward','A field journal for modern travel','blog'),('65','Nest','Home finance without the spreadsheet','saas'),('66','Redwood','Change management for real humans','service'),('67','Fable','Stationery for better thinking','product'),('68','The Commons','A work club for the self-directed','service'),('69','Pulse','A humane team health check','saas'),('70','Low Tide','Dispatches from the edge of ordinary','blog'),
('71','Canvas','Briefs that unlock great creative work','saas'),('72','Juniper','Botanical goods for daily rituals','product'),('73','Second Wind','A reset for overloaded teams','service'),('74','The Practical','A journal of useful things','blog'),('75','Drift','Build a life around what matters','saas'),('76','Anchor Point','Advisory for founders at the fork','service'),('77','Alto','Sound made for concentration','product'),('78','The Table','Small-group dinners for big ideas','service'),('79','Northwind','A planning tool for uncertain times','saas'),('80','The Commonplace','A personal archive for the curious','blog'),
('81','Foundry','Turn raw ideas into tested offers','saas'),('82','Sea Glass','Objects found, not forced','product'),('83','Good Signal','A sharper strategy in four weeks','service'),('84','The Quiet Office','Notes for an intentional career','blog'),('85','Current','Cash flow you can understand','saas'),('86','Bluebird','A studio for humane technology','service'),('87','Orchard','Fruit, flower, and pantry goods','product'),('88','The Relay','A newsletter for people who ship','blog'),('89','Compass','A personal dashboard for decisions','saas'),('90','The Open Road','Stories from people who changed course','blog'),
('91','Studio 9','Design support, exactly when needed','service'),('92','Kindred','Clothes made for repeat wear','product'),('93','Switchboard','Connect the work that matters','saas'),('94','The Bright Hour','A daily note for a better day','blog'),('95','Monument','Build a company people trust','service'),('96','Basin','Water, light, and quiet spaces','product'),('97','First Principles','A thinking partner for hard problems','service'),('98','The Ledger','An independent business journal','blog'),('99','Mosaic','See the whole picture at once','saas'),('100','Daybreak','Start something worth finishing','service')]
themes=[('#0b1020','#f6c453','#f7f4ed','Space Grotesk','radial'),('#151515','#ff6b4a','#fff7f1','DM Sans','sunset'),('#102a24','#b8e986','#eff8ee','Manrope','leaf'),('#f4eee4','#a64b2a','#1f2937','Fraunces','paper'),('#21143b','#e5b8ff','#fff8ff','Syne','aurora'),('#062d45','#63d8e6','#f3fbfc','Sora','ocean'),('#30110d','#f5a25d','#fff5e9','Libre Baskerville','ember'),('#191d29','#a7b5ff','#f4f5ff','IBM Plex Sans','grid'),('#2a1d12','#e8c27d','#fffaf0','Cormorant Garamond','grain'),('#101a16','#f2f0df','#f8f8f1','Plus Jakarta Sans','mono')]

def page(item,i):
 num,title,tag,kind=item; bg,accent,paper,font,motif=themes[i%len(themes)]; slug=title.lower().replace(' ','-').replace('&','and')
 cta={'saas':'Try it free','product':'Shop the collection','service':'Start a conversation','blog':'Read the latest'}[kind]
 desc={'saas':'A small, thoughtful tool for people who want more clarity and less noise.','product':'Made in small batches, designed for daily use, and meant to last.','service':'Focused help for the moment when good intentions need a clear next move.','blog':'A living collection of field notes, useful questions, and ideas worth carrying.'}[kind]
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — {tag}</title><link href="https://fonts.googleapis.com/css2?family={font.replace(' ','+')}:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>
:root{{--bg:{bg};--accent:{accent};--paper:{paper};--font:'{font}',sans-serif}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--paper);font-family:var(--font);overflow-x:hidden}}nav{{display:flex;justify-content:space-between;align-items:center;padding:26px 5vw;font-size:14px;position:relative;z-index:2}}.logo{{font-weight:800;letter-spacing:-.04em;font-size:20px}}nav a{{color:inherit;text-decoration:none;margin-left:24px;opacity:.75}}.hero{{min-height:calc(100vh - 80px);display:grid;place-items:center;text-align:center;padding:50px 7vw;position:relative;isolation:isolate}}.hero:before{{content:"";position:absolute;inset:8% 12%;background:radial-gradient(circle at 50% 35%,{accent}55,transparent 42%),linear-gradient(135deg,transparent,{accent}12);filter:blur(1px);z-index:-1;border-radius:50%;animation:float 8s ease-in-out infinite}}.orb{{position:absolute;width:min(42vw,430px);height:min(42vw,430px);border:1px solid {accent}88;border-radius:47% 53% 62% 38%;animation:spin 24s linear infinite;z-index:-1}}.orb:nth-child(2){{width:min(55vw,570px);height:min(28vw,300px);transform:rotate(45deg);animation-duration:31s}}.eyebrow{{text-transform:uppercase;letter-spacing:.2em;font-size:11px;color:var(--accent);font-weight:700}}h1{{font-size:clamp(3.4rem,10vw,9rem);line-height:.88;letter-spacing:-.08em;max-width:1050px;margin:22px auto}}.lead{{font-size:clamp(1rem,2vw,1.35rem);opacity:.78;max-width:560px;margin:25px auto 35px;line-height:1.5}}.cta{{display:inline-flex;align-items:center;gap:12px;background:var(--accent);color:{bg};padding:15px 23px;border-radius:999px;text-decoration:none;font-weight:700;transition:transform .25s,box-shadow .25s}}.cta:hover{{transform:translateY(-4px) scale(1.03);box-shadow:0 12px 35px {accent}55}}.strip{{background:var(--paper);color:{bg};padding:18px 5vw;display:flex;justify-content:center;gap:7vw;font-size:12px;letter-spacing:.08em;text-transform:uppercase;flex-wrap:wrap}}.below{{padding:90px 8vw;display:grid;grid-template-columns:repeat(3,1fr);gap:18px;background:var(--paper);color:{bg}}}.card{{padding:28px;border:1px solid {bg}22;border-radius:18px;min-height:150px;transition:transform .3s}}.card:hover{{transform:translateY(-8px)}}.card b{{color:{accent}}}@keyframes spin{{to{{transform:rotate(405deg)}}}}@keyframes float{{50%{{transform:scale(1.08) translateY(-12px)}}}}@media(max-width:650px){{nav a{{margin-left:10px}}.below{{grid-template-columns:1fr;padding:55px 7vw}}.hero{{min-height:80vh}}}}
</style></head><body><nav><div class="logo">{title}</div><div><a href="#about">About</a><a href="#contact">Contact</a></div></nav><main><section class="hero"><div class="orb"></div><div class="orb"></div><div><div class="eyebrow">{kind} · no. {num}</div><h1>{title}</h1><p class="lead">{tag}. {desc}</p><a class="cta" href="#contact">{cta} <span>↗</span></a></div></section><div class="strip"><span>Made with intention</span><span>For curious people</span><span>Less, but better</span></div><section class="below" id="about"><div class="card"><b>01</b><h3>A clear beginning</h3><p>Start with the thing you actually need. No maze, no jargon, no unnecessary ceremony.</p></div><div class="card"><b>02</b><h3>Room to move</h3><p>Thoughtful details, gentle motion, and enough space to make the experience feel like yours.</p></div><div class="card" id="contact"><b>03</b><h3>Come say hello</h3><p>Questions, ideas, or just curious? <a style="color:inherit" href="mailto:hello@example.com">Send a note →</a></p></div></section></main><script>document.querySelector('.cta').addEventListener('click',()=>document.body.classList.add('visited'))</script></body></html>'''

for i,item in enumerate(items): (pages/f'{item[0]}-{item[1].lower().replace(" ","-").replace("&","and")}.html').write_text(page(item,i))
# gallery
cards=''.join(f'<a class="tile t{i%10}" href="pages/{n}-{t.lower().replace(" ","-").replace("&","and")}.html"><small>{n} · {k}</small><strong>{t}</strong><span>{tag}</span></a>' for i,(n,t,tag,k) in enumerate(items))
(root/'index.html').write_text(f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>100 Living Landing Pages</title><style>*{{box-sizing:border-box}}body{{margin:0;background:#101114;color:#f5f1e8;font:16px system-ui,sans-serif}}header{{padding:9vw 7vw 5vw;display:flex;justify-content:space-between;align-items:end;gap:20px}}h1{{font-size:clamp(3rem,9vw,8rem);line-height:.85;letter-spacing:-.08em;margin:0;max-width:850px}}header p{{max-width:280px;color:#a8a49c;line-height:1.5}}.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:2px;background:#101114}}.tile{{min-height:220px;padding:22px;text-decoration:none;color:#111;display:flex;flex-direction:column;justify-content:space-between;transition:transform .3s,filter .3s;position:relative;overflow:hidden}}.tile:hover{{transform:scale(.97);filter:saturate(1.35)}}.tile strong{{font-size:28px;line-height:.95;letter-spacing:-.06em;max-width:180px}}.tile span{{font-size:13px;opacity:.7}}small{{font-size:11px;text-transform:uppercase;letter-spacing:.1em}}.t0{{background:#f6c453}}.t1{{background:#ff6b4a}}.t2{{background:#b8e986}}.t3{{background:#f4eee4}}.t4{{background:#e5b8ff}}.t5{{background:#63d8e6}}.t6{{background:#f5a25d}}.t7{{background:#a7b5ff}}.t8{{background:#e8c27d}}.t9{{background:#f2f0df}}footer{{padding:40px 7vw;color:#888;font-size:13px}}@media(max-width:600px){{header{{display:block}}header p{{margin-top:30px}}}}</style></head><body><header><h1>100<br>directions.</h1><p>A living gallery of differentiated landing page MVPs. Each page is a complete, functional concept — not a moodboard.</p></header><div class="grid">{cards}</div><footer>Generated as a rapid market-testing gallery · Every page has a working CTA and responsive layout.</footer></body></html>''')
print(f'generated {len(items)} pages')
